### ISSUE TITLE
Only downlink OR uplink have to be in spec to trigger Internet OK

### ISSUE THREAD

**Issue by PA7T** [shneezin/breitbandmessung#3]
I think in line 132 of speedtest.py the if condition is not correct:

`if result_up.text >= MIN_UPLOAD or result_down.text >= MIN_DOWNLOAD:`

The OR should be changed to an AND. I think both conditions have to be met, so you can consider your internet ok.
Let me know your thoughts.

**Comment by Shnezzin** [comment]
Thanks for the info.
There is an old line left over.
It has been adjusted.
